name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 1 * * *' # daily at 01:00 UTC
  workflow_dispatch:

jobs:
  cleanup-general:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Remove artifacts older than 60 days
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '60 days'
